---      # main playbook
- name: creating a playbook for user creation trough varibale declaring outside playbook
  hosts: all
  become: yes
  vars_files:
  - user.yml
  tasks:
  - name: creater user {{user2}}
    user:
      name: "{{user2}}"     # declaring a varibale in YAML scripting lang

#child playbook 
vi user.yml
user1: dipika
user2: amrutha
