---
- name: my test palybook
  hosts: all
  become: yes
  tasks:
    - name: to install httpd
      yum:
        name: httpd
        state: present
        notify: start apache  #start apache is match with handlers name: start apache
  handlers:
    - name: start apache
      service:
        name: httpd
        state: started
      
