---
- name: This play is to install tomcat and start its service
  hosts: all
  become: yes
  vars:
   version: 11
  tasks:


    - name: to install java
      yum:
        name: java
        state: present
      when: ansible_os_family == "RedHat"

    - name: to install java
      yum:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Downloading tomcat package on all nodes {{version}}
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-{{version}}/v{{version}}.0.10/bin/apache-tomcat-{{version}}.0.10.tar.gz
        dest: /opt

    - name: extracting tomcat
      unarchive:
        src: /opt/apache-tomcat-{{version}}.0.10.tar.gz
        dest: /opt
        remote_src: yes # after extracting it will verify again apache-tomcat-11.0.10 package whether that is present or not!!

    - name: starting .sh file
      command: /opt/apache-tomcat-{{version}}.0.10/bin/startup.sh





